---
title: "Vignette Title"
author: "Bob Rudis"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The release of `ggplot2` version `2.0` brought with it the ability to easily extend it from within external packages. The `ggalt` package provides additionals "stats", "geoms" and "coords", including:

- `coord_proj` : Similar to `coord_map` but using the PROJ.4 library/package- `geom_xspline` : Connect control points/observations with an X-spline
 [geom]
- `stat_xspline` : Connect control points/observations with an X-spline [stat]- `geom_bkde` :	Display a smooth density estimate (uses `KernSmooth::bkde`)
 [geom]- `stat_bkde` :	Display a smooth density estimate (uses `KernSmooth::bkde`)
 [stat]- `geom_bkde2d` :	Contours from a 2d density estimate. (uses `KernSmooth::bkde2D`)
 [geom]- `stat_bkde2d` :	Contours from a 2d density estimate. (uses `KernSmooth::bkde2D`)
 [stat]- `stat_ash` : Compute and display a univariate averaged shifted histogram (polynomial kernel) (uses `ash::ash1`/`ash::bin1`)
 [stat]
## Vignette Info

N